name: Build
on: [push, pull_request]

jobs:
  build:
    runs-on: windows-2019
    steps:
    - name: Checkout current build target
      uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    - name: Create build directory
      run: New-Item -ItemType Directory -Path build
    - name: Get Conan
      run: choco install -y Conan
    - name: CMake
      run: |
        cd build
        cmake ..
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1.0.0
    - name: Build
      run: |
        cd build
        msbuild yuzu.sln
